name: SteelCode Consulting - Mobile and Web development
description: Freelance mobile and web developer, specialized in Android, Ruby on Rails, Xamarin solutions, etc.
url: http://steelcode.net
markdown: redcarpet
pygments: false
timezone: Europe/Madrid
encoding: UTF-8
baseurl: /steelcode

permalink: /blog/:year/:month/:day/:title
paginate: 15
paginate_path: "blog/page:num"
