name: SteelCode Consulting - Mobile and Web development
description: Freelance mobile and web developer, specialized in Android, Ruby on Rails, Wordpress, PHP, etc.
url: http://steelcode.net
timezone: Europe/Madrid
encoding: UTF-8
highlighter: rouge

permalink: /blog/:year/:month/:day/:title
paginate: 15
paginate_path: "blog/page:num"

gems: ["jekyll-paginate"]

exclude: ["serve","Gemfile","Gemfile.lock","Vagrantfile","deploy","ideas.txt"]
